name: openai_access
on: [pull_request, push] 

env:
    ## Sets environment variable
  SECRET_TOKEN: ${{secrets.SECRET_KEY}}    

jobs:
  job1:
    runs-on: self-hosted 
    steps:
      - name: step 1
        run: echo "The API key is:${{env.SECRET_TOKEN}}"
